xpack.security.authc.token.enabled: false

xpack.security.authc.realms:
  file.file1:
    order: 0

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.keystore.type: PKCS12
xpack.security.http.ssl.keystore.path: {{install_root_path}}/config/x-pack/{{node_name}}/{{node_name}}.p12

xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.keystore.type: PKCS12
xpack.security.transport.ssl.keystore.path: {{install_root_path}}/config/x-pack/{{node_name}}/{{node_name}}.p12
