{# see https://www.elastic.co/guide/en/elasticsearch/reference/current/ml-settings.html #}
{%- if ml_max_open_jobs is defined %}
xpack.ml.max_open_jobs: {{ml_max_open_jobs}}
{%- endif %}
{%- if ml_max_machine_memory_percent is defined %}
xpack.ml.max_machine_memory_percent: {{ml_max_machine_memory_percent}}
{%- endif %}
{%- if ml_max_model_memory_limit is defined %}
xpack.ml.max_model_memory_limit: {{ml_max_model_memory_limit}}
{%- endif %}
{%- if ml_node_concurrent_job_allocations is defined %}
xpack.ml.node_concurrent_job_allocations: {{ml_node_concurrent_job_allocations}}
{%- endif %}