name: Docker Build and Test
on:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['linux/amd64', 'linux/arm64']
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: 'v0.9.1'
      - uses: actions/checkout@v4
        with:
          path: 'opensearch-benchmark-git'
      - name: Docker Build ${{ matrix.platform }}
        run: |
            docker buildx version
            cp -a opensearch-benchmark-git/* ./
            echo "Disable VERSION arg to enter docker build test mode"
            PLATFORM=${{ matrix.platform }}
            PLATFORM=`echo $PLATFORM | tr '/' '-'`
            docker buildx build --platform ${{ matrix.platform }} --build-arg BUILD_ENV=testing --build-arg BUILD_DATE=`date -u +%Y-%m-%dT%H:%M:%SZ` -f "docker/Dockerfile" -t "osb/osb-$PLATFORM" -o type=docker .
            docker images | grep "osb/osb-$PLATFORM"
