name: Docker Build
on:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['linux/amd64', 'linux/arm64']
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        # Workaround for a memory allocation layout bug in QEMU,
        # triggered by a kernel update to Linux machine images.
        # Note that this is not an actual fix.
        with:
          image: tonistiigi/binfmt:qemu-v7.0.0-28

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build ${{ matrix.platform }}
        run: |
            docker buildx version
            tag=osb/osb-`echo ${{ matrix.platform }} | tr '/' '-'`
            set -x
            docker buildx build --platform ${{ matrix.platform }} --build-arg VERSION=`cat version.txt` --build-arg BUILD_DATE=`date -u +%Y-%m-%dT%H:%M:%SZ` -f docker/Dockerfile -t "$tag" -o type=docker .
            set +x
            docker images | grep "$tag"
