name: CI Actions
on: [pull_request]
jobs:
  Unit-Tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Clone pyenv
        run: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
      - name: Run the CI build script
        run: bash .ci/build.sh build
        env:
          BENCHMARK_HOME: env.GITHUB_WORKSPACE
